projects:
  reactamplified:
    schemaPath: amplify/backend/api/reactamplified/build/schema.graphql
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
